[package]
name = "fme"
version = "0.1.6"
edition = "2021"

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_yaml = "0.9.32"
walkdir = "2.4.0"
yaml-front-matter = "0.1.0"
